2021-03-01 11:57:15,226 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 11:57:15,226 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 11:57:15,346 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 11:57:15,346 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 12:15:39,188 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 12:15:39,188 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 12:17:39,197 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/bb7a6c8d-7677-43cd-81d0-8bc757c3642b/window/current/size
2021-03-01 12:17:39,197 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/bb7a6c8d-7677-43cd-81d0-8bc757c3642b/window/current/size
2021-03-01 12:23:39,355 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 12:23:39,355 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 14:13:53,582 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179771ED730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 14:13:53,582 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179771ED730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 14:13:55,589 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001797719ECA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 14:13:55,589 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001797719ECA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 14:13:57,593 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179782494F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 14:13:57,593 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179782494F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/9eff76e1-4875-4878-a9a7-c21dd0fefc40
2021-03-01 15:08:54,278 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 15:08:54,278 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 15:09:03,939 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 15:09:03,939 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 16:00:11,849 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 16:00:11,849 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 16:00:20,976 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 16:00:20,976 - logger.py[line:67] - INFO: 网络考试录制用例failed
2021-03-01 16:36:15,942 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170F08E1520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
2021-03-01 16:36:15,942 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170F08E1520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
2021-03-01 16:36:17,949 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170EFEA8A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
2021-03-01 16:36:17,949 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170EFEA8A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
2021-03-01 16:36:19,954 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170F0ABB730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
2021-03-01 16:36:19,954 - connectionpool.py[line:751] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000170F0ABB730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session/b0f9b378-f20d-45a9-9103-700652bcbcfc
